[package]
name = "xi-lsp-lib"
version = "0.1.0"
repository = "https://github.com/google/xi-editor"
description = "The base library for implementing LSP Plugins for Xi"
authors = ["betterclever <paliwal.pranjal83@gmail.com>"]

[dependencies]
languageserver-types = "0.41.0"
serde_json = "1.0.19"
jsonrpc-lite = "0.5.0"
url = "1.7.0"

[dependencies.xi-plugin-lib]
path = "../plugin-lib"

[dependencies.xi-core-lib]
path = "../core-lib"

[dependencies.xi-rope]
path = "../rope"

[dependencies.xi-trace]
path = "../trace"